FROM node:14-alpine3.16 as moduler
COPY package.json .
RUN npm i --production

FROM node:14-alpine3.16 as builder
WORKDIR /app
COPY package.json .
RUN npm i
COPY . .
RUN npm run build

FROM nginx:stable-alpine
WORKDIR /app/academy-app
COPY --from=moduler node_modules .
COPY --from=builder /app/dist .
RUN mkdir /app/nginx
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80